---
env:
  node: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: latest

rules:
  no-underscore-dangle: 0
  comma-dangle: 0
  import/extensions: [
    "error",
    "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
  ]
  no-console: 0
  no-unused-expressions: 0
