---
env:
  node: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: latest

rules:
  no-underscore-dangle: 0
  comma-dangle: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
  - error
  - ignorePackages
  - js: always
  no-console: 0
  no-unused-expressions: 0
