---
env:
  node: true

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

parserOptions:
  ecmaVersion: latest

rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
  comma-dangle: ["error", "never"],
  import/extensions: [
    "error",
    "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
  ],
  no-console: "off",
  no-unused-expressions: ["error", { "allowTernary": true }]
